### PR TITLE
Provide Assertj helpers

### LINKED ISSUE #7: Refactor to multimodule project and create test-fixtures artifact
When using Gradle you can have in the same project `testFixtures` folder that creates classess accessible in tests and is published as separate artifact. I don't know how it works in Maven, but probably it has to be done as separate sub project.

I would like to add them custom AssertJ assertion for this type. Then it would be easier to test methods that returns this value.
Proposed class looks like this:

```java
package com.github.sviperll.result4j;

import com.github.sviperll.result4j.Result;
import java.util.function.Consumer;
import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.Assertions;

public class ResultAssert<R, E> extends AbstractAssert<ResultAssert<R, E>, Result<R, E>> {

  private ResultAssert(Result<R, E> actual) {
    super(actual, ResultAssert.class);
  }

  public static <R, E> ResultAssert<R, E> assertThat(Result<R, E> actual) {
    return new ResultAssert<>(actual);
  }

  public ResultAssert<R, E> isError() {
    isNotNull();

    Assertions.assertThat(actual.isError()).describedAs("Check if Result is an Error").isTrue();

    return this;
  }

  public ResultAssert<R, E> isSuccess() {
    isNotNull();

    Assertions.assertThat(actual.isError()).describedAs("Check if Result is a Success").isFalse();

    return this;
  }

  public ResultAssert<R, E> hasErrorEqualTo(E expectedError) {
    isNotNull();

    Assertions.assertThat(actualError()).describedAs("Check Result Error").isEqualTo(expectedError);

    return this;
  }

  public ResultAssert<R, E> hasErrorThat(Consumer<E> consumer) {
    isNotNull();

    consumer.accept(actualError());

    return this;
  }

  public ResultAssert<R, E> hasSuccessEqualTo(R expectedSuccess) {
    isNotNull();

    Assertions.assertThat(actualSuccess())
        .describedAs("Check Result Success")
        .isEqualTo(expectedSuccess);

    return this;
  }

  public ResultAssert<R, E> hasSuccessThat(Consumer<R> consumer) {
    isNotNull();

    consumer.accept(actualSuccess());

    return this;
  }

  private E actualError() {
    if (actual instanceof Result.Error(E error)) {
      return error;
    }
    throw failure("Expected Result to be Error but was Success");
  }

  private R actualSuccess() {
    if (actual instanceof Result.Success(R result)) {
      return result;
    }
    throw failure("Expected Result to be Success but was Error");
  }
}
```

I could create PR to convert project to multimodule, but it's been a while since I was using Maven.

What do you think about that?
If it is OK, maybe you can switch to multimodule?
I can convert it to Gradle, but not sure if can handle all your conventions (checkstyle, publishing).

### PR DESCRIPTION
**Pull request by sviperll**
Fixes #7

@marcindabrowski

 1. PTAL at the code, you may want to add some code review comments
 2. lets discuss an API a little more before finalizing.

In #10, you provided an example of the "that"-style method usage.

We assume the following `Result`-value:

````java
    Result result = Result.success(List.of("one", "two", "three"));
````

and the following imports:

````java
    import static com.github.sviperll.result4jassertj.ResultAssert.assertThat;
    import static org.assertj.core.api.Assertions.assertThat;
````

I see a several ways assertions can be written:

 1. option

    ````java
    assertThat(result)
            .isSuccess()
            .hasSuccessThat(
                    success ->
                            Assertions.assertThat(success)
                                    .hasSize(3)
                                    .containsExactlyInAnyOrder("three", "two", "one")
            );
    ````

 2. option

    ````java
    assertThat(result)
            .isSuccess()
            .hasSuccessThat(
                    success ->
                            success.asInstanceOf(InstanceOfAssertFactories.list(String.class))
                                    .hasSize(3)
                                    .containsExactlyInAnyOrder("three", "two", "one")
            );
    ````

 3. option

    ````java
    assertThat(result)
            .isSuccess()
            .hasSuccessThat()
            .asInstanceOf(InstanceOfAssertFactories.list(String.class))
            .hasSize(3)
            .containsExactlyInAnyOrder("three", "two", "one");
    ````

If we do with static-imports, like `assertj` promotes

````java
    import static org.assertj.core.api.InstanceOfAssertFactories.list;
````

we can get 2 or 3 even shorter:

 1. ...

 2. option

    ````java
    assertThat(result)
            .isSuccess()
            .hasSuccessThat(
                    success ->
                            success.asInstanceOf(list(String.class))
                                    .hasSize(3)
                                    .containsExactlyInAnyOrder("three", "two", "one")
            );
    ````

 3. option

    ````java
    assertThat(result)
            .isSuccess()
            .hasSuccessThat()
            .asInstanceOf(list(String.class))
            .hasSize(3)
            .containsExactlyInAnyOrder("three", "two", "one");
    ````

That said, I've found a precedent for such methods in assertj itself and there they use another form, something that can be written as

 1. ...

 2. ...

 3. ...

 4. option

    ````java
    assertThat(result)
            .isSuccess()
            .extractingValue(as(list(String.class)))
            .hasSize(3)
            .containsExactlyInAnyOrder("three", "two", "one");
    ````

See [AbstractObjectAssert::extracting](https://www.javadoc.io/static/org.assertj/assertj-core/3.26.3/org/assertj/core/api/AbstractObjectAssert.html#extracting(java.util.function.Function,org.assertj.core.api.InstanceOfAssertFactory)) and [AbstractOptionalAssert::get](https://www.javadoc.io/static/org.assertj/assertj-core/3.26.3/org/assertj/core/api/AbstractOptionalAssert.html#get(org.assertj.core.api.InstanceOfAssertFactory)).

I think we should go with the 4th option, like the following:

````java
class ResultAssert<T, E> extends AbstractObjectAssert<ResultAssert<T, E>, Result<T, E>> {
    public <A extends AbstractAssert<?, ?>> A extractingValue(InstanceOfAssertFactory<?, A> assertFactory) {
        return extracting(ResultAssert::getValueOrFail, assertFactory);
    }
    private T getValueOrFail(Result<T, E> result) {
        if (!(result instanceof Result.Success(var value)))
            throw fail("expecting result to be success");
        return value;
    }
}
````

WDYT?

### CODE REVIEW

**Comment by marcindabrowski** [comment]
Hey, below is my 5 cents.

### Review

1. Looks good, but I taught about removing AssertJ bom from pom file. Since we are using only one library from them, I think that adding version to `assertj-core` is enough. Otherwise, everyone who will use `result4j` will automatically import the bom file.
2. Can you put back my name in `author` tag on `ResultAssert`? File can have multiple author tags, and I feel as partial author of this file.
3. What about moving all test to `result4j-assertj` and using `ResultAssert` in every test? It will validate how the assert can be use at the same time. And since two modules are build, there is no need to run the same tests twice.

### ResultAssert
I was also thinking about the assertion and ability to use [satisfies](https://www.javadoc.io/static/org.assertj/assertj-core/3.26.3/org/assertj/core/api/AbstractAssert.html#satisfies(java.util.function.Consumer...)) method.

Then we can define `isError` as:
```java
public ObjectAssert<E> isError() {
    isNotNull();

    if (actual instanceof Result.Error(E error)) {
        return Assertions.assertThat(error);
    }
    throw failure("Expected Result to be Error but was Success");
}
```

and then we can use any assertion method of the error, or if the error is not common type, just use  `satisfies` method to apply custom assertion like this:
```java
 ResultAssert.assertThat(result)
     .isError()
     .satisfies(error ->
          Assertions.assertThat(error)
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessage("Name is invalid")
     );
``` 
The same change will be applied to `isSuccess`.

With this approach user will have ability to anything he want, and `isError` and `isSuccess` will return instance of the assertion corresponding to its type (if it will be a common AssertJ type, or the one registred with `AssertProvider`).

After that change we can remove `hasErrorEqualTo`, `hasErrorThat`, `hasSuccessEqualTo`, `hasSuccessThat`, `actualError` and `actualSuccess` methods, and assert will have only two methods `isError` and `isSuccess`.

WDYT?

**Comment by marcindabrowski** [comment]
Hey, I agree with almost everything, but don't agree with that:



> I do not like it, because with such `isError`-method we will get that:
> 
> ```java
>  ResultAssert.assertThat(result).isNotNull().isError();
> ```
> 
> is not the same as
> 
> ```java
>  ResultAssert.assertThat(result).isError().isNotNull();
> ```

Actually this one will be always possible:

```java
ResultAssert.assertThat(result).isNotNull().hasErrorThat().isNotNull();
```

First `.isNotNull()` refers to `result` object, the latter to the error `value`.

Of course we can name the method as `hasErrorThat`, but the question is how this method should looks like?

```java
public ObjectAssert<E> hasErrorThat() {
    isNotNull();

    if (actual instanceof Result.Error(E error)) {
        return Assertions.assertThat(error);
    }
    throw failure("Expected Result to be Error but was Success");
}
```

or somehow differently?

Do you want me to make a pull request with this change?

**Comment by sviperll** [comment]
> First `.isNotNull()` refers to result object, the latter to the error value

Yes, this is mostly about the naming. The following I can understand

````java
assertThat(result).isNotNull().hasErrorThat().isNotNull();
````

, but the same with the `isError`-name looks like a puzzler:

````java
assertThat(result).isNotNull().isError().isNotNull();
````

> how this method should looks like?

I think what you've written should work.

> Do you want me to make a pull request with this change?

I was going to go through the changes and release a new version by the end of the week. The remaining changes that I know of:

- [ ] change `hasErrorThat` to be as one that we have discussed
- [ ] remove unnecessary specializations (`hasErrorEqualTo`, `hasSuccessEqualTo`)
- [ ] convert all the tests in `ResultCollectorsTest.java` in `result4j-assertj` to use `ResultAssert` or remove those that do not need `ResultAssert`
- [ ] check the generated flattened pom.xml in `result4j` that it doesn't contain any unnecessary dependencies/boms

You can do any of these to speed things up, but I was also planning to do some of this today and tomorrow.

**Comment by marcindabrowski** [comment]
I made #12 PR with:
* change hasErrorThat to be as one that we have discussed
* remove unnecessary specializations (hasErrorEqualTo, hasSuccessEqualTo)
* convert all the tests in ResultCollectorsTest.java in result4j-assertj to use ResultAssert or remove those that do not need ResultAssert

You can cherry pick my commit to this PR.

**Comment by sviperll** [comment]
I've merged your changes and added some more modifications on top:

 * I've retained `isError` and `isSuccess` methods, because they may sometimes be useful on their own and they serve a good introduction when we explain what `ResultAssert` class provides.
 * I've renamed `hasSuccessThat` to `hasValueThat`, I think it is more understandable this way...
 * I've added some more documentation

Take a look. If there is no strong disagreement, then I'll merge this tomorrow and release version 1.2.

**Comment by marcindabrowski** [comment]
Few things.

1. You wrote in the Javadoc of the class:
    ```java
    // Standard AsserJ assertions:
    import static org.assertj.core.api.Assertions.assertThat;
    
    // Assertions for the Result-values
    import static com.github.sviperll.result4jassertj.ResultAssert.assertThat;
     ```
    
    Actually you can't import two static `assertThat` methods at the same time.
    So only `com.github.sviperll.result4jassertj.ResultAssert.assertThat` should be imported.

2. In javadoc of `hasErrorThat` you shouldn't use `{@link ResultAssert#hasErrorThat()}` because it is pointing to the javadoc in which this link is. The same happens to `hasValueThat`.

3. And to be honest I don't like the name `hasValueThat`. Why it can't be `hasSuccessThat`?
You have `isSuccess`, and `hasValueThat` do not correspond with that. What about `hasSuccessValueThat` or `hasSuccessThatValueIs`?
But then we should also adjust method for `Error`.

WDYT?

**Comment by marcindabrowski** [comment]
And one more thing. Why assertion class is in `result4jassertj`. Why it can't be at the same package as `Result` class?

**Comment by sviperll** [comment]
> 1. You wrote in the Javadoc of the class: ...
>     
>     Actually you can't import two static `assertThat` methods at the same time.
>     So only `com.github.sviperll.result4jassertj.ResultAssert.assertThat` should be imported.
> 

I do believe this is wrong. You *can* import multiple methods with the same name. JLS implicitly allows it, see for instance  [section 15.12.2.1](https://docs.oracle.com/javase/specs/jls/se23/html/jls-15.html#jls-15.12.2.1).  There it says

> <...> if the form of the method invocation expression is *MethodName* - that is, a single Identifier - then the search for potentially applicable methods also examines all member methods that are imported by single-static-import declarations and static-import-on-demand declarations of the compilation unit where the method invocation occurs ([§7.5.3](https://docs.oracle.com/javase/specs/jls/se23/html/jls-7.html#jls-7.5.3), [§7.5.4](https://docs.oracle.com/javase/specs/jls/se23/html/jls-7.html#jls-7.5.4)) and that are not shadowed at the point where the method invocation appears.

Here it says "examines *all* member methods that are imported" and in [section 7.5.3](https://docs.oracle.com/javase/specs/jls/se23/html/jls-7.html#jls-7.5.3) there is a restriction on the static imports for the *types* with the same name, but *no restrictions* for the multiple static imports of *methods* with the same name.

Moreover, this is not only allowed, it is also the recommended way to use AssertJ. See [the Providing an entry point for all custom assertions section](https://assertj.github.io/doc/#assertj-core-custom-assertions-entry-point) in the AssertJ documentation. There is an explicit example that does:

````java
import static my.project.MyProjectAssertions.assertThat;
import static org.assertj.core.api.Assertions.assertThat;
````

And this is the recommended way to do it. This is actually a reason, why [the Creating your own assertion class section](https://assertj.github.io/doc/#assertj-core-custom-assertions-creation) recommends that you create "An entry point to your specific assertion class to use with static import", this is because Java is to select the most specific version of `assertThat`-methods from all statically-imported variables.

> 3. And to be honest I don't like the name `hasValueThat`. Why it can't be `hasSuccessThat`?
> You have `isSuccess`, and `hasValueThat` do not correspond with that. What about `hasSuccessValueThat` or `hasSuccessThatValueIs`?
> But then we should also adjust method for `Error`.
> 
>
> WDYT?

I like `hasValueThat` better than `hasSuccessThat` and slightly better than `hasSuccessValueThat`. We have `Result::orOnErrorThrow` method that is named like this, because the "success value" is the main thing, that we do not even need to name it, otherwise the method would be called `Result::getSuccessValueOrThrow` and I think the current name is the right choice. The type is called `Result` to mean the result of some operation. The operation can be "successful", but not the result, the result is just there after the successful operation.

I think I'm mostly ok with choosing `hasSuccessValueThat` as a name instead of the `hasValueThat` as a name, if you really think that it's better, but I would retain other names, so in the end we will get the following set of methods in the `ResultAssert`-class:

 * isSuccess
 * isError
 * hasSuccessValueThat
 * hasErrorThat
 
Are you ok with that?

**Comment by sviperll** [comment]
> And one more thing. Why assertion class is in result4jassertj.
> Why it can't be at the same package as Result class, or

We need a separate artifact to depend on in tests.

The goals for result4j is to

 * have minimal bloat and
 * minimal dependencies.

Following these goals we do not want to bundle support of assertj in the same artifact as a main `Result`-class.

Also `result4j` is to support Java-modules (JPMS). JPMS doesn't support split-packages, i. e. multiple modules providing the same package, so we need to have a different package name then the one used for the main artifact.

> at least in result4j.assertj?

This is more stylistic and only partly technical. When we have multiple packages I prefer organizing them following the layering or dependency-graph. I. e. if I see `pkg.a.b` and `pkg.a.b.c`, I assume that `pkg.a.b.c` is an implementation detail used by the `pkg.a.b`. `result4j` and `result4j.assertj` do not have this relationship they share the same level of abstraction, neither is an implementation detail of another. They are more like a two areas of the overarching API-surface, so that's why they are defined as a packages on the same level `result4j` and `result4jassertj`. Another way around is to move `result4j` into something like `result4j.core`, so that we will get

 * `result4j.core`
 * `result4j.assertj`

Probably it's a good solution, but this will break backwards compatibility, so we have to stay within the `result4j` package.

Practically I don't think package name is that big of a problem, so I would probably leave package-naming like it is right now.

**Comment by marcindabrowski** [comment]
1. Sorry for confusion with static import of `assertThat`. You are right.
I commented about it, because I'm writing tests with Spock in Groovy, and there it is impossible.
2.  I'm OK with `hasSuccessValueThat`, and keeping other methods unchanged.
3. I don't wanted `ResultAssert` to be in the same Java artifact as `Result` class - it was me who asked about creating subproject. What I like in my projects to have all classes supporting tests in the same package as core classes. 
But I don't agree with the logic you wrote about package tree. For me `result4j.assertj` means that `assertj` contains AssertJ assertions for `result4j` package. Even Spring has such packages - https://docs.spring.io/spring-boot/api/java/org/springframework/boot/test/context/assertj/AssertableApplicationContext.html. But at the end decision is yours.

**Comment by sviperll** [comment]
@marcindabrowski What do you think about renaming `result4j-assertj` to `assertj-result4j` and correspondingly `com.github.sviperll.result4jassertj` module and package to `com.github.sviperll.assertj.result4j`?

**Comment by marcindabrowski** [comment]
> @marcindabrowski What do you think about renaming `result4j-assertj` to `assertj-result4j` and correspondingly `com.github.sviperll.result4jassertj` module and package to `com.github.sviperll.assertj.result4j`?

It is OK to me

**Pull request merged**
