### PR TITLE
Fix Continuous Integration Checks GitHub workflow

### PR DESCRIPTION
**Pull request by marcindabrowski**

### CODE REVIEW

**Comment by marcindabrowski** [comment]
I forgot to add `v` before version number.
Now it is working - https://github.com/sviperll/result4j/actions/runs/11969945110/job/33371673662

But I don't see in the log info about executed tests. Maybe we should run something else than `validate`?

You can also add `Continuous Integration Checks / Run checks` to required tasks in branch protection.

**Comment by sviperll** [comment]
I've changed `validate` to `verify` that runs tests.
I've got stuck with the new sonatype publishing process. But I think I've finally make it work. The new version `1.1.3` should be published soonish...

**Comment by marcindabrowski** [comment]
I see it https://central.sonatype.com/artifact/com.github.sviperll/result4j/versions.

Still not in https://mvnrepository.com/artifact/com.github.sviperll/result4j but it is working for me.

Thanks!

**Comment by marcindabrowski** [comment]
But the version in Readme is now SVG , and it shows the wrong number, and can't be copied.
It also is not working well with Dark Theme for GitHub.

**Pull request merged**
